owner: moductor
repo: status

sites:
  - name: Website
    url: https://moductor.dev/

status-website:
  name: Moductor Status
  cname: status.moductor.dev
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
